### ISSUE TITLE
FlysystemOtherManager function definition incompatible

### ISSUE THREAD

**Issue by renardss-hub** [danhunsaker/laravel-flysystem-others#13]
Hi all, 
There seems to be an issue when using laravel 8.61.0 and danhunsaker/laravel-file-system-others v1.4.0:

Declaration of Danhunsaker\Laravel\Flysystem\FlysystemOtherManager::resolve($name) should be compatible with Illuminate\Filesystem\FilesystemManager::resolve($name, $config = NULL)

FlysystemOtherManager.php row 397

re-define protected function resolve($name) to
protected function resolve($name, $config = NULL)

and 399
$adapter = parent::resolve($name); to
$adapter = parent::resolve($name, $config);

Fixed the issue for me. 
Cheers!

**Comment by danhunsaker** [comment]
See #11, #12
