### ISSUE TITLE
Error Message when trying to publish vendor 

### ISSUE THREAD

**Issue by joaonzangoII** [danhunsaker/laravel-flysystem-others#2]
Steps to reproduce
1. Run `php artisan vendor:publish --provider=Danhunsaker\\Laravel\\Flysystem\\FlysystemOtherServiceProvider --force `
2. Error in terminal `Can't locate path: <0>`

**Comment by danhunsaker** [comment]
Please upgrade to the latest version and see if that fixes the issue.  Sorry about the bug!

**Comment by joaonzangoII** [comment]
@danhunsaker I have tested and it works now, thanks for the fix, I am closing the issue :)
