### ISSUE TITLE
Error with smb driver, throws class not found

### ISSUE THREAD

**Issue by matthiascw** [danhunsaker/laravel-flysystem-others#5]
I am trying to use the robgridley/flysystem-smb driver but I am facing a `Class 'Icewind\SMB\Server' not found` error when I am trying to access the smb disk in `config/filesystems.php`.
```
'smb' => [
    'driver'   => 'smb',
    'host'     => '',
    'username' => '',
    'password' => '',
    'path'     => '',
],
```

Credentials are filled accordingly.

**Comment by danhunsaker** [comment]
You need to make sure you install all of the dependencies `robgridley/flysystem-smb` requires. It probably lists them as `suggested` if you can select more than one.

**Comment by matthiascw** [comment]
There are no suggestions for `robgridley/flysystem-smb` in my `composer.lock`. The dependencies of the package are:

- `icewind/smb: ^3.0|^2.0`
- `icewind/streams` as a requirement from icewind/smb

Which I have installed.

**Comment by danhunsaker** [comment]
Oh good. Then that class should be installed as well.

Which means something was changed somewhere that needs to be adapted.

**Comment by danhunsaker** [comment]
OK, so Icewind changed some class names between 2.x and 3.x. I'll have to try to support both.

**Comment by danhunsaker** [comment]
If you can try again with the latest version, this should be fixed. Sorry for the delay getting to it.
