### ISSUE TITLE
Laravel 7 support

### ISSUE THREAD

**Issue by Wulfheart** [danhunsaker/laravel-flysystem-others#9]
Hello,

please update the package to support Laravel 7. ;-)

**Comment by JamesPJ** [comment]
probably Laravel 7 and Laravel 8 would be better

**Comment by danhunsaker** [comment]
Agreed. Adding both in just a moment.

**Comment by danhunsaker** [comment]
`v1.4.0` supports Laravel 7 and 8. :slightly_smiling_face:
